# Generated by Django 6.0.7 on 2026-08-03 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('membros', models.ManyToManyField(blank=True, help_text='Usuários que têm permissão para visualizar/acessar este projeto.', related_name='projetos_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
