# Generated by Django 6.0.7 on 2026-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoIPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('profiles_usados', models.JSONField(default=list, help_text='Lista de perfis/handles monitorados neste IPD')),
            ],
            options={
                'verbose_name': 'Projeto IPD',
                'verbose_name_plural': 'Projetos IPD',
                'db_table': 'projeto_ipd',
            },
        ),
        migrations.CreateModel(
            name='ProjetoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('projetos_ipd', models.ManyToManyField(blank=True, related_name='projetos_cliente', to='client.projetoipd')),
            ],
            options={
                'verbose_name': 'Projeto Cliente',
                'verbose_name_plural': 'Projetos Clientes',
                'db_table': 'projeto_cliente',
            },
        ),
    ]
