# Generated by Django 6.0.7 on 2026-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoipd',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
