# Generated by Django 6.0.7 on 2026-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_projetoipd_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetoipd',
            name='slug',
        ),
        migrations.AddField(
            model_name='projetocliente',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
