# Generated by Django 6.0.7 on 2026-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_projetoipd_slug_projetocliente_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetocliente',
            name='tipo_ipd',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2')], default=1),
        ),
    ]
