# Generated by Django 6.0.7 on 2026-09-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_projetocliente_tipo_ipd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetocliente',
            name='projetos_ipd',
        ),
        migrations.RemoveField(
            model_name='projetoipd',
            name='profiles_usados',
        ),
        migrations.CreateModel(
            name='ProjetoClienteIPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles_usados', models.JSONField(default=list, help_text='Lista de perfis monitorados para este IPD neste cliente específico')),
                ('projeto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.projetocliente')),
                ('projeto_ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.projetoipd')),
            ],
            options={
                'db_table': 'projeto_cliente_ipd',
                'unique_together': {('projeto_cliente', 'projeto_ipd')},
            },
        ),
    ]
