# Generated by Django 6.0.7 on 2026-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_projetocliente_projetos_ipd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetocliente',
            name='projetos_ipd',
            field=models.ManyToManyField(blank=True, related_name='projetos_cliente', through='client.ProjetoClienteIPD', to='client.projetoipd'),
        ),
    ]
