# Generated by Django 6.0.7 on 2026-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_projetocliente_projetos_ipd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de exibição (ex: Cor Primária)', max_length=50)),
                ('chave', models.SlugField(help_text='Identificador no código (ex: primary, success, warning)', unique=True)),
                ('codigo_hex', models.CharField(help_text='Código HEX (ex: #007bff ou #fff)', max_length=7)),
            ],
            options={
                'verbose_name': 'Cor Padrão',
                'verbose_name_plural': 'Cores Padrão',
            },
        ),
    ]
