# Generated by Django 6.0.7 on 2026-08-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=150)),
                ('fama', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('engaj', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mob', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interesse', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ipd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data', models.DateField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('hash_indice', models.CharField(editable=False, max_length=64, unique=True)),
                ('projeto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_ipd', to='client.projetocliente')),
                ('projeto_ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_ipd', to='client.projetoipd')),
            ],
            options={
                'verbose_name': 'Medição IPD',
                'verbose_name_plural': 'Medições IPD',
                'db_table': 'ipd_medicoes',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id_post', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.DateField(db_index=True)),
                ('projeto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='client.projetocliente')),
                ('projeto_ipd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='client.projetoipd')),
                ('ipds', models.ManyToManyField(blank=True, related_name='conteudos', to='score.ipd')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'db_table': 'ipd_conteudos',
            },
        ),
        migrations.AddConstraint(
            model_name='ipd',
            constraint=models.UniqueConstraint(fields=('projeto_ipd', 'profile', 'data'), name='unique_ipd_profile_data'),
        ),
    ]
