# Generated by Django 6.0.7 on 2026-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='ipds',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='link_post',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='profile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
