# Generated by Django 6.0.7 on 2026-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_projetoipd_slug_projetocliente_slug'),
        ('score', '0002_remove_conteudo_ipds_conteudo_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='projeto_cliente',
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='projeto_ipd',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='projeto_ipd',
            field=models.ManyToManyField(blank=True, to='client.projetoipd'),
        ),
    ]
