# Generated by Django 6.0.7 on 2026-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_projetoipd_slug_projetocliente_slug'),
        ('score', '0003_remove_conteudo_projeto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['-data', '-curtidas'], 'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdos'},
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['profile', 'data', '-curtidas'], name='idx_cnt_prof_data_curt_desc'),
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['data', '-curtidas'], name='idx_cnt_data_curt_desc'),
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['profile', 'data'], name='idx_cnt_profile_data'),
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['data', '-comentarios'], name='idx_cnt_data_coment_desc'),
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['-data_registro'], name='idx_cnt_data_registro_desc'),
        ),
    ]
