# Generated by Django 6.0.7 on 2026-08-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_conteudo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='titulo',
        ),
    ]
