# Generated by Django 6.0.7 on 2026-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_remove_conteudo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='link_post',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
