# Generated by Django 6.0.7 on 2026-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_conteudo_link_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='categoria_tema',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
