# Generated by Django 6.0.7 on 2026-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_conteudo_categoria_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipd',
            name='projeto_cliente',
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='categoria_tema',
            field=models.CharField(db_index=True, default='Outros', max_length=255),
        ),
    ]
