# Generated by Django 6.0.7 on 2026-09-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_projetoipd_slug_projetocliente_slug'),
        ('score', '0008_remove_ipd_projeto_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoExecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_executivos', to='client.projetocliente')),
            ],
            options={
                'indexes': [models.Index(fields=['projeto', 'mes_referencia'], name='score_resum_projeto_0913c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'mes_referencia'), name='unique_resumo_projeto_mes')],
            },
        ),
    ]
