# Generated by Django 6.0.7 on 2026-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_projetoipd_slug_projetocliente_slug'),
        ('score', '0009_resumoexecutivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumoexecutivo',
            options={'verbose_name': 'Resumo Executivo', 'verbose_name_plural': 'Resumos Executivos'},
        ),
        migrations.RemoveConstraint(
            model_name='resumoexecutivo',
            name='unique_resumo_projeto_mes',
        ),
        migrations.RemoveIndex(
            model_name='resumoexecutivo',
            name='score_resum_projeto_0913c0_idx',
        ),
        migrations.AddField(
            model_name='resumoexecutivo',
            name='hash_insumo',
            field=models.CharField(db_index=True, default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumoexecutivo',
            name='mes_referencia',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='resumoexecutivo',
            index=models.Index(fields=['projeto', 'mes_referencia', 'hash_insumo'], name='score_resum_projeto_a55852_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumoexecutivo',
            constraint=models.UniqueConstraint(fields=('projeto', 'mes_referencia'), name='unique_resumo_executivo_projeto_mes'),
        ),
    ]
