# Generated by Django 6.0.7 on 2026-09-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_alter_resumoexecutivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd',
            name='interesse',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
