# Generated by Django 6.0.7 on 2026-09-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_projetocliente_projetos_ipd'),
        ('score', '0011_alter_ipd_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='id',
            field=models.CharField(default='', editable=False, max_length=500, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='id_post',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='conteudo',
            name='projeto_ipd',
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['projeto_ipd', 'profile', 'data'], name='idx_cnt_ipd_prof_data'),
        ),
        migrations.AddIndex(
            model_name='conteudo',
            index=models.Index(fields=['projeto_ipd', 'data', '-curtidas'], name='idx_cnt_ipd_data_curt_desc'),
        ),
        migrations.AddConstraint(
            model_name='conteudo',
            constraint=models.UniqueConstraint(fields=('id_post', 'projeto_ipd'), name='unique_post_per_ipd'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='projeto_ipd',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='client.projetoipd'),
            preserve_default=False,
        ),
    ]
