# Generated by Django 6.0.7 on 2026-08-04 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projetos_cliente', models.ManyToManyField(blank=True, related_name='usuarios_autorizados', to='client.projetocliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'db_table': 'permissoes_usuario',
            },
        ),
    ]
